#spring:  
#  datasource:
#    url: jdbc:mysql://13.229.55.43:3306/ticketdbtool
#    password: PexNqZ7wymUZmMgS
#    username: root
#    driver-class-name: "com.mysql.jdbc.Driver"
#  jwt:
#  secret: 7GX#wEk_8F@?EiY-@?e?h!U@WS:ijW
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update      
#  